MAP_SLUGS = {
    "2d": "2D",
    "acapulco": "Acapulco",
    "ad_astra": "Ad Astra",
    "ad_infinitum": "Ad Infinitum",
    "aequabilis": "Aequabilis",
    "aether": "Aether",
    "after_hours": "After Hours",
    "agrostid": "Agrostid",
    "amphitheater": "Amphitheater",
    "annealing_iv": "Annealing IV",
    "apocalypse_ctw": "Apocalypse CTW",
    "apostle": "Apostle",
    "arabia": "Arabia",
    "araxa": "Araxa",
    "autumn_breeze": "Autumn Breeze",
    "bamboo_valley_v": "Bamboo Valley V",
    "banana_split": "Banana Split",
    "belvedere": "Belvedere",
    "blocks_ctw": "Blocks CTW",
    "bloom": "Bloom",
    "blossom_ctw": "Blossom CTW",
    "brittlebush_ii": "Brittlebush II",
    "cargo": "Cargo",
    "catscratch": "Catscratch",
    "chestnut": "Chestnut",
    "circus_ctw": "Circus CTW",
    "citadel": "Citadel",
    "clayclay": "ClayClay",
    "clearcut": "Clearcut",
    "coconut_mald": "Coconut Mald",
    "colorado": "Colorado",
    "columbia_ctw": "Columbia CTW",
    "constellation": "Constellation",
    "corrupted_paradise_ctw": "Corrupted Paradise CTW",
    "cyril": "Cyril",
    "dead_noon": "Dead Noon",
    "deciduous_nights": "Deciduous Nights",
    "deepwind_jungle": "Deepwind Jungle",
    "desert_country": "Desert Country",
    "desert_eclipse": "Desert Eclipse",
    "desolate_gully_ctw": "Desolate Gully CTW",
    "downforce": "Downforce",
    "dromedary": "Dromedary",
    "duality": "Duality",
    "dynamo": "Dynamo",
    "edo": "Edo",
    "emergency_meeting": "Emergency Meeting",
    "empire": "Empire",
    "enchanted": "Enchanted",
    "epsilon": "Epsilon",
    "exitium": "Exitium",
    "exogrid": "Exogrid",
    "expedition": "Expedition",
    "factorio_mainbus": "Factorio Mainbus",
    "fairy_tales_2_a_tale_or_two": "Fairy Tales 2: A Tale or Two",
    "fairy_tales_2_mini": "Fairy Tales 2: Mini",
    "fairy_tales_metamorphose": "Fairy Tales: Metamorphose",
    "fall_of_babylon": "Fall of Babylon",
    "feel_good_inc": "Feel Good Inc.",
    "firum_ctw": "Firum CTW",
    "flush_vibes_ii": "Flush Vibes II",
    "fourchette": "Fourchette",
    "frost": "Frost",
    "garf": "Garf",
    "gethsemane": "Gethsemane",
    "gobi": "Gobi",
    "golden_drought": "Golden Drought",
    "golden_drought_iii": "Golden Drought III",
    "golden_drought_iv": "Golden Drought IV",
    "golden_drought_v": "Golden Drought V",
    "gongua_ctw": "Gongua CTW",
    "goo_lagoon": "Goo Lagoon",
    "green_gem_ctw": "Green Gem CTW",
    "green_gem_ctw_mini": "Green Gem CTW Mini",
    "greenhill": "Greenhill",
    "gridlock_2": "Gridlock 2",
    "hallows": "Hallows",
    "harbor_ctw": "Harbor CTW",
    "hauoli_mau_lanui": "Hau'oli Mau Lanui",
    "hello_world": "Hello World",
    "hillside_daydream": "Hillside Daydream",
    "hobbit_ctw": "Hobbit CTW",
    "honeycombed": "Honeycombed",
    "hotel_overcast": "Hotel Overcast",
    "huanxiang": "Huanxiang",
    "icecream_sandwiched_ii": "Icecream Sandwiched II",
    "infernal_shadow": "Infernal Shadow",
    "ingwaz": "Ingwaz",
    "istana_ctw": "Istana CTW",
    "jungle_beat": "Jungle Beat",
    "kanto": "Kanto",
    "keipha_ctw": "Keipha CTW",
    "kerskyn": "Kerskyn",
    "kingdom": "Kingdom",
    "krager": "Krager",
    "level_up": "Level Up",
    "long_distance": "Long Distance",
    "lupa": "Lupa",
    "lupain": "Lupain",
    "madness_on_rails": "Madness on Rails",
    "mahatma": "Mahatma",
    "mame_i_shrunk_the_pvpers": "Mame, I Shrunk the PvPers",
    "mini_drought": "Mini Drought",
    "mushroom_gorge": "Mushroom Gorge",
    "nether_war_ctw": "Nether War CTW",
    "nextgen": "NextGen",
    "no_mans_land": "No Man's Land",
    "nobles_district": "Noble's District",
    "nyxis": "Nyxis",
    "oaken_meadow_mini": "Oaken Meadow Mini",
    "oasis_ctw": "Oasis CTW",
    "oceano_ctw": "Oceano CTW",
    "onier": "Onier",
    "oumuamua": "Oumuamua",
    "ouroboros": "Ouroboros",
    "outback_mini": "Outback Mini",
    "outback_outback_edition": "Outback: Outback Edition",
    "outlyne": "Outlyne",
    "paddos": "Paddo's",
    "peloponnesia": "Peloponnesia",
    "pineium_ctw": "Pineium CTW",
    "pirates_i": "Pirates I",
    "pixelmix": "PixelMix",
    "prisma_ctw": "Prisma CTW",
    "race_for_victory": "Race for Victory",
    "race_for_victory_2": "Race for Victory 2",
    "race_for_victory_3": "Race for Victory 3",
    "raceway": "Raceway",
    "renegade": "Renegade",
    "research_base": "Research Base",
    "rice": "Rice",
    "rind_rushers_ii": "Rind Rushers II",
    "ringpull": "Ringpull",
    "ruedigers_octawool": "Ruediger's Octawool",
    "sakura_garden": "Sakura Garden",
    "sakura_garden_ii": "Sakura Garden II",
    "sanctum_wasser": "Sanctum Wasser",
    "santorini": "Santorini",
    "sheep_ctw": "Sheep CTW",
    "shroom_galaxy": "Shroom Galaxy",
    "smashcap": "Smashcap",
    "snow_level": "Snow Level",
    "split_strata": "Split Strata",
    "stalactites_a_land_down_under": "Stalactites: A Land Down Under",
    "standstill": "Standstill",
    "summertime_at_browns_farms": "Summertime at Brown's Farms",
    "super_happy_fun_world": "Super Happy Fun World",
    "sweetopia": "Sweetopia",
    "tangier": "Tangier",
    "thornwood": "Thornwood",
    "thunderbolt": "Thunderbolt",
    "timbered": "Timbered",
    "tohjo_falls_ii": "Tohjo Falls II",
    "townside_mini": "Townside Mini",
    "tranquility": "Tranquility",
    "tulip_mania": "Tulip Mania",
    "tulip_mania_ii": "Tulip Mania II",
    "tumbleweed": "Tumbleweed",
    "tusho_ctw": "Tusho CTW",
    "twisted": "Twisted",
    "two_tier": "Two Tier",
    "underpass": "Underpass",
    "vegas": "Vegas",
    "veld": "Veld",
    "vertex": "Vertex",
    "vesuvius": "Vesuvius",
    "villa_ii": "Villa II",
    "welcome_to_wool_square": "Welcome to Wool Square",
    "when_men_cried": "When Men Cried",
    "wholething": "Wholething",
    "winter_wakening": "Winter Wakening",
    "wintertime": "Wintertime",
    "witchs_potions": "Witch's Potions",
    "wits_end": "Wit's End",
    "xion": "Xion",
    "xunkohtli": "Xunkohtli",
    "yermo": "Yermo",
    "rntgn": "Röntgen"
}
