"""
Side-by-side layout vs island polygon debug plots.

Left panel  — decided layout (layout_decided.parquet if available, otherwise
              the layer configured in map_layouts.yaml, otherwise bedrock).
              Rendered as a coloured block image using the case-study palette.

Right panel — island polygons from map_context.json, coloured by team,
              with build region and POI markers.

Output: one PNG per map written to output/<map_slug>_layout_debug.png
        (output root, not inside the map subfolder — easy sequential review).

Usage:
    python scripts/plot_layout_island_debug.py
    # edit MAPS list below, or pass map slugs as CLI args:
    python scripts/plot_layout_island_debug.py tumbleweed ingwaz dynamo
"""

import json
import sys
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# ── project root on path ─────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'scripts'))

from common.visualization import draw_layout_image
from common.visualization.map_primitives import (
    draw_build_region, draw_island_outlines, draw_pois,
    map_base_legend_handles,
    BuildRegionStyle, IslandOutlineStyle, POIStyle,
)
from layout_analysis.map_layout_config import get_map_layout

# ── maps to plot (overridden by CLI args) ────────────────────────────
MAPS: list[str] = [
    'tumbleweed',
    'ingwaz',
    'dynamo',
]

OUTPUT_ROOT = ROOT / 'output'

_LAYER_FILES = {
    'y0':           'layout_y0.parquet',
    'bedrock':      'layout_bedrock.parquet',
    'lowest_solid': 'layout_lowest_solid.parquet',
    'top_surface':  'layout_top_surface.parquet',
}


# ── helpers ───────────────────────────────────────────────────────────

def _decided_layout_path(map_slug: str) -> Path | None:
    """Return the best available layout parquet for *map_slug*."""
    out = OUTPUT_ROOT / map_slug

    # 1. Preferred: layout_decided (generated by new pipeline)
    p = out / 'layout_decided.parquet'
    if p.exists():
        return p

    # 2. Configured layer from map_layouts.yaml
    cfg = get_map_layout(map_slug)
    if cfg and not cfg.skip:
        fname = _LAYER_FILES.get(cfg.layer)
        if fname:
            p = out / fname
            if p.exists():
                return p

    # 3. Fallback: bedrock
    p = out / 'layout_bedrock.parquet'
    if p.exists():
        return p

    return None


def _load_map_context(map_slug: str) -> dict | None:
    path = OUTPUT_ROOT / map_slug / 'map_context.json'
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def _layer_label(map_slug: str, path: Path) -> str:
    """Human label describing which layer file is being shown."""
    cfg = get_map_layout(map_slug)
    decided = OUTPUT_ROOT / map_slug / 'layout_decided.parquet'
    if path == decided:
        layer = cfg.layer if cfg else '?'
        excl = f', excl {cfg.exclude}' if cfg and cfg.exclude else ''
        return f'layout_decided  [{layer}{excl}]'
    stem = path.stem.replace('layout_', '')
    if cfg and not cfg.skip:
        return f'{stem}  (decided not yet generated — using configured layer)'
    return stem


# ── per-map plot ──────────────────────────────────────────────────────

def plot_map(map_slug: str) -> str:
    layout_path = _decided_layout_path(map_slug)
    ctx = _load_map_context(map_slug)

    if layout_path is None and ctx is None:
        return f'SKIP {map_slug} — no layout or map_context found'

    fig, (ax_l, ax_r) = plt.subplots(1, 2, figsize=(18, 9), layout='constrained')
    cfg = get_map_layout(map_slug)
    layer_str = cfg.layer if (cfg and not cfg.skip) else 'bedrock (default)'
    fig.suptitle(
        f'{map_slug}   |   configured layer: {layer_str}',
        fontsize=11, fontweight='bold',
    )

    # ── Left: coloured block image ───────────────────────────────────
    if layout_path is not None:
        df = pd.read_parquet(layout_path)
        draw_layout_image(ax_l, df)
        ax_l.set_title(_layer_label(map_slug, layout_path), fontsize=8)
    else:
        ax_l.text(0.5, 0.5, 'No layout data', transform=ax_l.transAxes,
                  ha='center', va='center', color='gray')
        ax_l.set_title('layout — no data', fontsize=8)

    ax_l.set_xlabel('X')
    ax_l.set_ylabel('Z')

    # ── Right: island polygons ────────────────────────────────────────
    if ctx is not None:
        has_build = draw_build_region(ax_r, ctx, style=BuildRegionStyle())

        # Draw normal islands without observer islands so they don't get team colour
        observer_ids = {isl['id'] for isl in ctx.get('islands', []) if isl.get('is_observer_island')}
        if observer_ids:
            ctx_no_obs = dict(ctx, islands=[i for i in ctx.get('islands', []) if i['id'] not in observer_ids])
        else:
            ctx_no_obs = ctx
        draw_island_outlines(
            ax_r, ctx_no_obs,
            style=IslandOutlineStyle(exterior_linewidth=1.0, exterior_alpha=0.95),
        )
        draw_pois(ax_r, ctx, style=POIStyle(spawn_size=120, wool_size=80))

        # Draw observer islands with a grey hatched style so they're clearly "excluded"
        for isl in ctx.get('islands', []):
            if isl.get('is_observer_island'):
                poly = isl.get('simplified_polygon')
                if poly and poly.get('exterior'):
                    pts = np.array(poly['exterior'])
                    ax_r.fill(pts[:, 0], pts[:, 1],
                              facecolor='none', edgecolor='grey', linewidth=1.5,
                              hatch='////', alpha=0.8, zorder=3)
                ax_r.text(
                    isl['center'][0], isl['center'][1],
                    'OBS', color='white', fontsize=5.5, ha='center', va='center',
                    fontweight='bold', zorder=9,
                    bbox=dict(boxstyle='round,pad=0.1', fc='grey', alpha=0.8, lw=0),
                )

        # Annotate each island: id + area
        for isl in ctx.get('islands', []):
            cx, cz = isl['center']
            ax_r.text(
                cx, cz,
                f"#{isl['id']}\n{isl['area']}bl",
                fontsize=4.5, ha='center', va='center', color='white',
                bbox=dict(boxstyle='round,pad=0.1', fc='black', alpha=0.45, lw=0),
                zorder=10,
            )

        ax_r.axis('equal')
        ax_r.invert_yaxis()

        n_islands = len(ctx.get('islands', []))
        symmetry_desc = ''
        sym_path = OUTPUT_ROOT / map_slug / 'symmetry.json'
        if sym_path.exists():
            with open(sym_path) as _sf:
                _sym = json.load(_sf)
            _detected = [s for s in _sym.get('global_symmetry', []) if s.get('detected')]
            if _detected:
                _p = max(_detected, key=lambda s: s.get('confidence', 0.0))
                symmetry_desc = f"  |  symmetry: {_p.get('description', _p.get('type', '?'))} ({_p['confidence']:.0%})"

        ax_r.set_title(
            f'Islands ({n_islands}){symmetry_desc}',
            fontsize=8,
        )

        legend_h = map_base_legend_handles(has_build_region=has_build)
        ax_r.legend(handles=legend_h, loc='upper right', fontsize=5.5,
                    framealpha=0.8, ncol=2)
    else:
        ax_r.text(0.5, 0.5, 'No map_context.json', transform=ax_r.transAxes,
                  ha='center', va='center', color='gray')
        ax_r.set_title('Islands — no data', fontsize=8)

    ax_r.set_xlabel('X')
    ax_r.set_ylabel('Z')

    out_path = OUTPUT_ROOT / f'{map_slug}_layout_debug.png'
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    return f'OK   {map_slug}  -> {out_path.name}'


# ── main ──────────────────────────────────────────────────────────────

def _read_symmetry_confidence(map_slug: str) -> Optional[float]:
    """Return primary symmetry confidence from symmetry.json, or None if absent/undetected."""
    sym_path = OUTPUT_ROOT / map_slug / 'symmetry.json'
    if not sym_path.exists():
        return None
    with open(sym_path) as f:
        sym = json.load(f)
    detected = [s for s in sym.get('global_symmetry', []) if s.get('detected')]
    if not detected:
        return None
    return max(s.get('confidence', 0.0) for s in detected)


def _maps_below_threshold(threshold: float) -> list[str]:
    """Return slugs of all maps whose displayed symmetry confidence (whole %) is below threshold."""
    results = []
    for sym_path in sorted(OUTPUT_ROOT.glob('*/symmetry.json')):
        slug = sym_path.parent.name
        confidence = _read_symmetry_confidence(slug)
        if confidence is None:
            continue
        # Compare as whole-number percentage to match the :.0% display in plot titles.
        # e.g. 0.9996 displays as "100%" and should be excluded at threshold=100.
        if round(confidence * 100) < round(threshold * 100):
            results.append((confidence, slug))
    results.sort()
    return [slug for _, slug in results]


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description='Layout + island debug plots')
    parser.add_argument('maps', nargs='*', help='Map slugs to plot (default: hardcoded MAPS list)')
    parser.add_argument('--threshold', type=float, metavar='PCT',
                        help='Plot all maps with primary symmetry confidence below this '
                             'percentage (0-100). Overrides positional map args.')
    args = parser.parse_args()

    if args.threshold is not None:
        maps = _maps_below_threshold(args.threshold / 100.0)
        print(f'Maps with symmetry confidence < {args.threshold}%: {len(maps)}')
    else:
        maps = args.maps if args.maps else MAPS

    print(f'Plotting {len(maps)} maps...')
    for slug in maps:
        status = plot_map(slug)
        print(f'  {status}')
    print('Done.')


if __name__ == '__main__':
    main()
